### ISSUE TITLE
not work, proxy

### ISSUE THREAD

**Issue by ruslanx3m** [0x0a0d/axios-socks5-agent#1]
not work .. freeze.

```
const axios = require('axios');
const SocksAgent = require('axios-socks5-agent');

const { httpAgent, httpsAgent } = new SocksAgent({ host: 'xx.xx.xx.xx', port: xxxx,  agentOptions: { keepAlive: true } });

axios
    .get('http://wtfismyip.com/json', { httpAgent, httpsAgent })
    .then(res => console.log(res.data))
    .catch(e => console.error(e));
```

**Comment by 0x0a0d** [comment]
I just test again with tor and it still works.
If you get freeze, you should check socks5 for sure that it still opens
> curl http://wtfismyip.com/json --socks5 127.0.0.1:9050
if your socks5 does not open and you dont want to freeze, you should add timeout to request config

axios
    .get('http://wtfismyip.com/json', { httpAgent, httpsAgent, **timeout: 30e3** })

**Comment by Cocophotos** [comment]
Hi,

Indeed, this issue occurred to me. This seems related to that issue: https://github.com/nodejs/node/issues/37510 which seems to be a Node issue and a http(s)-socks-client issue.

Best,

**Comment by minhna** [comment]
I have this "freeze" issue too. Node: v14.19.1, axios: v0.21.0. Problem solved with `socks-proxy-agent` package
